// Generated by CoffeeScript 1.6.3
var sock, zmq;

zmq = require('zmq');

sock = zmq.socket('push');

sock.bind('tcp://127.0.0.1:3000', function() {
  var seq;
  console.log({
    sending: 1
  });
  seq = 0;
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  return setTimeout((function() {
    sock.close();
    return console.log({
      closed: 1
    });
  }), 10000);
});
