// Generated by CoffeeScript 1.6.3
var seq, sock, zmq;

zmq = require('zmq');

sock = zmq.socket('push');

seq = 0;

sock.bind('tcp://127.0.0.1:3000', function() {
  var prevMem;
  console.log({
    sending: 1
  });
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  setInterval((function() {
    return sock.send(seq++);
  }), 0);
  prevMem = void 0;
  return setInterval((function() {
    var mem;
    mem = process.memoryUsage();
    if (prevMem != null) {
      console.log({
        delta: {
          rss: mem.rss - prevMem.rss,
          heap: {
            tot: mem.heapTotal - prevMem.heapTotal,
            used: mem.heapUsed - prevMem.heapUsed
          }
        }
      });
    }
    return prevMem = mem;
  }), 1000);
});
