// Generated by CoffeeScript 1.6.3
var seq, sock, zmq;

zmq = require('zmq');

sock = zmq.socket('push');

sock.bindSync('tcp://127.0.0.1:3000');

seq = 0;

setInterval((function() {
  return sock.send(seq++);
}), 0);

setInterval((function() {
  return sock.send(seq++);
}), 0);

setInterval((function() {
  return sock.send(seq++);
}), 0);

setInterval((function() {
  return sock.send(seq++);
}), 0);

setInterval((function() {
  return sock.send(seq++);
}), 0);

setInterval((function() {
  return sock.send(seq++);
}), 0);

setInterval((function() {
  return sock.send(seq++);
}), 0);

setInterval((function() {
  return sock.send(seq++);
}), 0);

setInterval((function() {
  return sock.send(seq++);
}), 0);

setInterval((function() {
  return sock.send(seq++);
}), 0);
