// Generated by CoffeeScript 1.6.3
var lastSecond, me, prev, seq, sock, subscribers, zmq;

zmq = require('zmq');

sock = zmq.socket('pull');

sock.connect('tcp://127.0.0.1:3000');

me = 0;

subscribers = 0;

seq = 0;

prev = 0;

sock.on('message', function(msg) {
  var delta;
  seq = parseInt(msg);
  delta = seq - prev;
  me = (seq % delta) + 1;
  subscribers = delta;
  return prev = seq;
});

lastSecond = 0;

setInterval((function() {
  var perSecond;
  perSecond = seq - lastSecond;
  lastSecond = prev;
  return console.log("subscriber " + me + " of " + subscribers + ", " + perSecond + " msg/second, total " + seq + " ");
}), 1000);
