// Generated by CoffeeScript 1.6.3
var first, lastSecond, me, messages, prev, seq, sock, subscribers, zmq;

zmq = require('zmq');

sock = zmq.socket('pull');

sock.connect('tcp://127.0.0.1:3000');

me = 0;

subscribers = 0;

seq = 0;

prev = 0;

first = void 0;

messages = [];

sock.on('message', function(msg) {
  var delta;
  seq = parseInt(msg);
  delta = seq - prev;
  me = (seq % delta) + 1;
  subscribers = delta;
  prev = seq;
  if (first == null) {
    first = seq;
  }
  return messages.push(seq);
});

process.on('SIGINT', function() {
  sock.close();
  return setTimeout((function() {
    console.log({
      last: prev
    });
    return process.exit(0);
  }), 2000);
});

lastSecond = 0;

setInterval((function() {
  var msgCount, perSecond;
  perSecond = seq - lastSecond;
  lastSecond = prev;
  msgCount = messages.length;
  messages.length = 0;
  return console.log("" + me + " of " + subscribers + ", global:[first: " + first + ", seq: " + seq + ", " + perSecond + " msg/s], local:[newLocalMessageCount: " + msgCount + "]");
}), 1000);
